[project]
name = "greenbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio[ffmpeg]>=2.37.3",
    "json-numpy>=2.1.1",
    "modal>=0.68",
    "mujoco>=3.10.0",
    "pillow>=12.3.0",
    "pyarrow>=25.0.0",
    "requests>=2.34.2",
]
